# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Peter Theill'
tagline:          'Peter Theill and his font viewer, webcam, free asp chat system, free asp sms sender, free form filler, free asp bookmark manager'
description:      "Hello!<br />I'm <a href='/about'>Peter Theill</a> and this is my personal web site"
url:              http://theill.com

author:
  name:           'Peter Theill'
  url:            https://theill.com/cv

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde