# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'The Ill Site'
tagline:          'Peter Theill and his font viewer, webcam, free asp chat system, free asp sms sender, free form filler, free asp bookmark manager'
description:      'Personal web site of Peter Theill'
url:              http://theill.com

author:
  name:           'Peter Theill'
  url:            https://theill.com/cv

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde